language: android
# Enable container-based infrastructure ##START##
sudo: false
# Enable container-based infrastructure ##END##
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository
jdk:
  - oraclejdk8
env:
  - CI=true
branches:
  only:
    - master
before_install:
# Signature stub ##START##
    - echo "stub keystore" > boats.keystore
    - echo "stub storage pwd" > keystore.pwd
    - echo "stub key pwd" > key.pwd
# Signature stub ##END##
# Mark Gradle as executable ##START##
    - chmod +x ./gradlew
# Mark Gradle as executable ##END##
script:
    - sh scripts/debugVerify.sh
    - sh scripts/debugUnitTests.sh
after_failure:
    - cat "/home/travis/build/stoyicker/boats-xkcd/staticAnalysisReport/presentation/lint.html"
    - cat "/home/travis/build/stoyicker/boats-xkcd/staticAnalysisReport/data/lint.html"