language: android
# Enable container-based infrastructure ##START##
sudo: false
# Enable container-based infrastructure ##END##
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository
jdk:
  - oraclejdk8
branches:
  only:
    - master
before_install:
# Signature stub ##START##
    - echo "stub keystore" > stub.keystore
    - echo "stub storage pwd" > stubstorage.pwd
    - echo "stub key pwd" > stub.pwd
# Signature stub ##END##
# Mark Gradle as executable ##START##
    - chmod +x ./gradlew
# Mark Gradle as executable ##END##
script:
    - sh scripts/verifyDebug.sh
    - sh scripts/unitTests.sh